name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Vérifier index.html
      - name: Vérifier la présence du fichier index.html
        run: |
          if [ -f src/frontend/index.html ]; then
            echo "Le fichier index.html existe"
          else
            echo "Erreur : index.html n’existe pas!"
            exit 1
          fi

      # Build & Deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_WATER_05379E003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src/frontend"
          api_location: ""
          output_location: "."

      # Attendre que le site soit disponible
      - name: Attendre que le site soit disponible
        run: |
          echo "Attente du déploiement..."
          for i in {1..20}; do
            if curl -s -o /dev/null -w "%{http_code}" https://thankful-water-05379e003.1.azurestaticapps.net/ | grep "200"; then
              echo "Site disponible "
              break
            fi
            echo "Pas encore prêt... nouvelle tentative"
            sleep 15
          done

      # Vérifier l'URL avant Lighthouse
      - name: Tester l'URL avant Lighthouse
        run: curl -I https://thankful-water-05379e003.1.azurestaticapps.net/

      # Lighthouse CI avec assertions
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./.lighthouserc.json
          uploadArtifacts: false








